### ISSUE TITLE
Info request: watchdown timer 

### ISSUE THREAD

**Issue by FredFoo** [Heckie75/kodi-addon-timers#12]
Moin Heckie! 

I was hoping you could help me with finding my way into this.

I was looking for a timer that would get a setting like 30 minutes use of the player per day in this profile and if that time is up logout from that profile. If you login again: sorry, time is up, bye bye :))

From your experience, is the playtime available in a system variable, i.e. the time the player was used during a certain period? Or is that something you would need to fiddle together yourself? I was thinking the player would be the best place to start so it does not matter if I watch a file or some youtube content. 

Ideas?

**Comment by Heckie75** [comment]
@FredFoo 

You must implement a so called Monitor in order to get events for start playing etc. 

Then you could sum up the played time and store is somewhere, e.g. in settings file. 

Then you must implement a Monitor that starts with Kodi and displays the message if the time limit is reached. 

However, this issue is not related to this addon.

**Comment by FredFoo** [comment]
Thanks a lot! I got some ideas from your code already, thanks for the hint! True, not related to the addon but at least somehow in hte realm of timers :))) 

Thanks again!
