### ISSUE TITLE
need assistance with pausing instead of stopping

### ISSUE THREAD

**Issue by siennamediatest** [Heckie75/kodi-addon-timers#21]
I'm setting up kodi to use in a nursing home for people with dementia. All the videos I'm playing are youtube playlists, because addon timers doesn't work directly with the youtube plugin, I add the media link into the timers.json
The system is configured to be used with a very simple remote control. The power button controls play/pause, and the tv automatically turns off when idle.
I'm trying to set timers so that there are playlists set for certain times, but I also want residents to be able to decide when to watch. For example: -playlist starts at 8:30 after breakfast. I want to be able to set times where playback pauses for lunch, snack breaks, afternoon nap, dinner, and bed. I can set it so that the youtube playlist stops at those times, and set a timer for another playlist to pick up, but then the video is stopped, and the resident has no way of reactivating it until the next playlist starts. Is there a way to set pause as the end state of a playlist? Can I set a 'pause' timer that overlaps with a playlist that otherwise goes through the day? Under 'media_action' in timers.json can I set a function to press a key?

**Comment by Heckie75** [comment]
Hi @siennamediatest,

I'm glad to hear that my addon is used for such senseful use cases. 

I've understood that you want to pause a playlist for a certain period, resume it after some time. Have you already thought about using another timer that plays something that is silent and or a gong sound. 

```
Timer 1      |>>>>>>>>------------------->>>>>>>>>>>>|              Timer with youtube playlist
Timer 2               |>>>>--------------|                          Timer with another playlist or single title (maybe just silence)
      t |----t1-------t2-----------------t3----------t4-------->
```

**Global setting**
Misc > Seek to correct time if timer starts belately -> on

**Settings of Timer 1**
- end after -> time or duration
- media action --> play at start and stop at end
- resume -> on

**Settings of Timer 2**
- end after -> time or duration
- media action --> play at start and stop at end
- resume -> on
- repeat -> on                              

I have tried this solution. I works at least for _normal_ media. I was not able to test it for youtube playlists. 

Maybe you can send me the URL of the youtube media that you want to play. 

BTW: In order to see the _resume_ setting you must change to _advanced_ mode in settings dialog.

Best regards,
Heckie

**Comment by siennamediatest** [comment]
Thanks a lot for your response! I hadn't considered playing different material, and that actually opens up some interesting possibilities of displaying landscapes/weather info/clock information/family albums.

**Comment by Heckie75** [comment]
Fine, I'm waiting for your feedback if this works for you finally.

**Comment by Heckie75** [comment]
@siennamediatest I have added a new media action that pauses the player. It is not merged into the official repositoty yet. 

However, you can take a look at it by installing it from the zip file: [script.timers.3.4.0.zip](https://github.com/Heckie75/kodi-addon-timers/blob/script.timers.3.4.0/script.timers.3.4.0.zip?raw=true)

**Comment by siennamediatest** [comment]
I found a different method, and have implemented gpio buttons on the device to trigger a timed break. I'm having another issue and I think you might know what I'm doing wrong. I'm trying to set up a gpio button that triggers a youtube playlist through the youtube addon. I'm got the button working and have it trigger xbmc.executebuiltin("RunPlugin(youtubepluginplaylistpath)"). It works sometimes, but mostly crashes kodi. 
With your plugin, youtube playlist is triggered perfectly if I put plugin://plugin.video.youtube/play/?playlist_id=PLopMpzJBXsBRXEqODSoiDxCI2QvEPR1mB&order=shuffle&play=1 in the timers.json file under path. Looking through your addon, it looks like you have an external player set up?

**Comment by Heckie75** [comment]
I think that the Timer addon calls YouTube like this:

PlayMedia("plugin://plugin.video.youtube/play/?playlist_id=PLopMpzJBXsBRXEqODSoiDxCI2QvEPR1mB&order=shuffle&play=1")

Instead of utilizing RunPlugin

see also Line 62ff in https://github.com/Heckie75/kodi-addon-timers/blob/master/script.timers/resources/lib/player/player_utils.py
