### ISSUE TITLE
Timer doesn't start

### ISSUE THREAD

**Issue by bttfba** [Heckie75/kodi-addon-timers#30]
Hi Heckie, how are you? Fabio again
I have the last versions installed (Kodi 20.1 and Timers 3.5)
I have one main timer set, playing the content of a directory from 8:30 till 22:30 (looping)
Then I set some other timers, the first at 9:30, then 11:30 and so, about every two hours.
It happens sometime that some of these timers doesn't start: problems with Widevine? or something else? in the log there are several errors ...
Attached the log, you can start from the  end, where you see at 9:30 of April 7 the timer didn't start.
Thanks for your help, as usual!
Fabio
[kodi - Copia 230407.log](https://github.com/Heckie75/kodi-addon-timers/files/11177197/kodi.-.Copia.230407.log)

**Comment by Heckie75** [comment]
Hi @bttfba,

According the log file the scheduler works as expected. There is the event that triggers your Disney addon:

![Screenshot_20230407-102641-855](https://user-images.githubusercontent.com/10388395/230572876-979b3b74-a34c-4e12-935e-c74075e9ca4f.png)

I have also recognized that sometimes the player isn't able to start playing, e.g. in my case TV programs by utilizing the Zattoo addon esp. if the addon hasn't played s.th. else before. It's more s.th. related to the integrated player. If I find the root cause I'll let you know.

**Comment by bttfba** [comment]
Thank you Heckie
Let me know in case i have to open an issue for some other process
Thanks
fabio

**Comment by bttfba** [comment]
@Heckie75 , i think it is a concurrency of two events disturbing each other. Maybe two different video players trying to start at the same time ...
It happens only at that particular moment, same movie starts 2 hours later and there are no problems. Could you tell me which is the video player involved? I'll open an issue against that.
Thaanks
Fabio

**Comment by Heckie75** [comment]
@bttfba according the log file I think that the problem could be the playlist mattino_2 playing since 8:30. May be there are two events aß you said, i.e.
A) changing the title of playlist mattino_2 to  C:\Dati\Programmazione\Mattino_2\082_stacco_sala_recenti.m4v, implicitly since prev. title ist over
B) starting the video stream explicitly by timers addon

Try the following
Play mattino_2 playlist in random mode (option 1) or change order of titles (by renaming files, option 2) so that the title change doesn't match timer event at 9:30

Option 3: Start mattino_2 playlist a little earlier or a little later. There is a new feature that allows you to schedule to the second (toggle to expert mode)

Let me know if this helps.

**Comment by Heckie75** [comment]
@bttfba So it has been a concurrency problem as you expected. Perfect. 

BTW: In version 3.6. notifications will be improved in case of overlapping timers and multiple events. Let me know if you have  ideas of other features?
